header
YourMentor-org/SpaceStations pull request #9
Opened 2017-05-16 20:24 UTC by qsok3d

2017-05-17 00:53 UTC, Afelua requested changes

2017-05-17 00:53 UTC, Afelua commented on fonts/fonts.css
> +    	 url('montserrat-bold.ttf') format('truetype'),
Подправить выравнивание (на одном уровне)

2017-05-17 00:53 UTC, Afelua commented on style.css
> +  padding: 0 180px 0 180px;
Можно писать краткой формой: 0 180px - нет необходимости дублировать. Проверить для всех случаев.

2017-05-17 00:53 UTC, Afelua commented on style.css
> +  width: 175px;
Задавать конкретную ширину плохо, поскольку у нас планируется адаптив. В подобных случаев лучше воздержаться от конкретного значений width и использовать max-width.

2017-05-17 00:53 UTC, Afelua commented on style.css
> +  width: 175px;
Проверить для всех случаев, для width: 620px; вижу аналогичный комментарий.

2017-05-17 00:53 UTC, Afelua commented on style.css
> +.header__button{
У всех кнопок button добавляем свойства:
    cursor: pointer;  - http://htmlbook.ru/css/cursor
    outline: none; - http://htmlbook.ru/css/outline

2017-05-17 00:53 UTC, Afelua commented on style.css
> +  line-height: 34px;
line-height задаем относительное, http://www.frontendlabs.ru/top-15-css3-fails-2/ п. 4

2017-05-17 00:53 UTC, Afelua commented on style.css
> +  line-height: 34px;
Проверить везде

2017-05-17 00:53 UTC, Afelua commented on style.css
> +  padding: 0 125px 0 145px;
Большие отступы ради правильного задания разметки лучше не делать. К тому же, в данном случае header__about предполагается ровно по центру. Для этих случаев есть варианты центрирования http://www.internet-technologies.ru/articles/article_2108.html

2017-05-17 00:53 UTC, Afelua commented on style.css
> +  font-family: 'Montserrat-Bold';
При указание нестандартного шрифта всегда полагается указывать совокупность стандартных на случай, если кастомный не подгрузился.
Пример - font-family: 'Open Sans', Arial, Helvetica, sans-serif;

2017-05-17 00:53 UTC, Afelua commented on style.css
> +  padding-bottom: 60px;
Для .header__subtitle отступ задается снизу, а для .header__heading - сверху. Лучше везде придерживаться единых стандартов.

2017-05-17 00:53 UTC, Afelua commented on style.css
> +  width: 720px;
Не поверю, что 720, они намного меньше. Да и необходимости в задании их ширины нет (блок должен подстраиваться под кол-во кнопок)

2017-05-17 00:53 UTC, Afelua commented on style.css
> +  height: 60px;
Тоже плохая идея задавать конкретную высоту, особенно у родителя. Блоки должны быть максимально подстраиваться под элементы, в данном случае под кнопки. Т.е. мы не у родителя должны говорить: "введи единый стандарт на все", и у детей должны эти стандарты описывать, и уже родитель должен выглядеть подобным образом потому, что "дети такие".

2017-05-17 00:53 UTC, Afelua commented on style.css
> +  height: 60px;
Задать конкретную высоту у кнопок - плохая практика. Лучше использовать line-height или padding.

2017-05-17 00:57 UTC, Afelua commented on style.css
> +.header__pic{
У всех картинок с тегом img, который не планируются меняться на адаптиве, прописываем высоту и ширину в атрибутах тега, а не в виде стиля, - так картинка будет грузится быстрее.

2017-05-18 18:15 UTC, qsok3d commented on style.css
> +  padding: 0 125px 0 145px;
ок

2017-05-18 18:16 UTC, qsok3d commented on fonts/fonts.css
> +    	 url('montserrat-bold.ttf') format('truetype'),
ок

2017-05-18 18:17 UTC, qsok3d commented on style.css
> +  padding: 0 180px 0 180px;
+

2017-05-18 18:18 UTC, qsok3d commented on style.css
> +  width: 175px;
+

2017-05-18 18:18 UTC, qsok3d commented on style.css
> +  font-family: 'Montserrat-Bold';
+

2017-05-18 18:29 UTC, qsok3d commented on style.css
> +.header__button{
+

2017-05-18 18:35 UTC, qsok3d commented on style.css
> +  line-height: 34px;
+

2017-05-18 18:45 UTC, qsok3d commented on style.css
> +  width: 720px;
+

2017-05-18 18:45 UTC, qsok3d commented on style.css
> +  height: 60px;
+

2017-05-18 18:50 UTC, qsok3d commented on style.css
> +  height: 60px;
+

2017-05-18 19:15 UTC, qsok3d commented on style.css
> +  padding-bottom: 60px;
+

2017-05-18 19:15 UTC, qsok3d commented on style.css
> +.header__pic{
+

2017-05-18 21:55 UTC, Afelua requested changes

2017-05-18 21:55 UTC, Afelua commented on style.css
> +  height: 440px;
height тоже плохо задавать, лучше указывать max-height

2017-05-18 21:55 UTC, Afelua commented on style.css
> +  padding-bottom: 75px;
Избавиться от большого padding-bottom

2017-05-18 21:55 UTC, Afelua commented on style.css
> +.slider__button{
Задаем outline

2017-05-18 21:55 UTC, Afelua commented on style.css
> +  flex-direction: row;
Излишнее св-во, по умолчанию row

2017-05-18 21:55 UTC, Afelua commented on style.css
> +  margin-right: 18px;
Задать через margin с обоих сторон

2017-05-18 21:55 UTC, Afelua commented on style.css
> +  height: 290px;
Плохо указывать height, проверить везде

2017-05-18 21:55 UTC, Afelua commented on style.css
> +.services__pic{
Убрать пустой класс

2017-05-18 21:55 UTC, Afelua commented on style.css
> +  text-align: center;
Св-во стоит задать для всего services__item

2017-05-18 21:55 UTC, Afelua commented on index.html
> +            <div class="services__logo">
div services__logo нельзя вкладывать внутри li, http://www.frontendlabs.ru/top-15-css3-fails-2/, п. 10

2017-05-18 21:55 UTC, Afelua commented on index.html
> +            <p class="services__text">This is Photoshop`s version of Lorem<br>Ipsum. proim gravida nibh vel velit auctor<br>aliquet mauris.</p>
Плохо делать br, т.к. при уменьшении экрана будет масштабироваться некорректно. Весь текст стоит прогонять через https://www.artlebedev.ru/tools/typograf/

2017-05-21 08:28 UTC, qsok3d commented on style.css
> +  flex-direction: row;
+

2017-05-21 08:29 UTC, qsok3d commented on style.css
> +.slider__button{
+

2017-05-21 08:31 UTC, qsok3d commented on style.css
> +  text-align: center;
+

2017-05-21 08:31 UTC, qsok3d commented on style.css
> +.services__pic{
+

2017-05-21 20:46 UTC, qsok3d commented on index.html
> +            <p class="services__text">This is Photoshop`s version of Lorem<br>Ipsum. proim gravida nibh vel velit auctor<br>aliquet mauris.</p>
+

2017-05-21 20:46 UTC, qsok3d commented on index.html
> +            <div class="services__logo">
+

2017-05-21 20:47 UTC, qsok3d commented on style.css
> +  margin-right: 18px;
+

2017-05-21 20:49 UTC, qsok3d commented on style.css
> +  height: 440px;
+

2017-05-22 22:18 UTC, Afelua requested changes

2017-05-22 22:18 UTC, Afelua commented on style.css
>  .services{
Выше у контейнера base__nav есть ошибки. Во-первых, это - не навигация, и потому элемент nav тут не уместен. Во-вторых,     padding: 0 180px (большое значение) - некрасиво, делаем через максимальную ширину элемента services или base__nav.

2017-05-22 22:18 UTC, Afelua commented on style.css
>  .services{
.base - ошибка с заданием height (не нужно ограничивать), сделать отступ через padding

2017-05-22 22:18 UTC, Afelua commented on index.html
>                <img src="img/logo-web.png" alt="" class="services__pic services__pic_web" width="40px" height="40px">
Обычно px в атрибутах не пишут, просто 40. Проверить везде.

2017-05-22 22:18 UTC, Afelua commented on style.css
> +  background-color: #fff;
Такой стандартный background-color: #fff; стоит задавать у body. Он будет наследоваться дочерними элементами.

2017-05-22 22:18 UTC, Afelua commented on style.css
> +  height: 535px;
Убираем высоту! Было сообщено об этой ошибке ранее

2017-05-22 22:18 UTC, Afelua commented on style.css
> +  padding-top: 60px;
.timetable__text -  padding-top: 60px;
.timetable__main - margin-top: 50px; 
Стоит определиться, margin или padding (однотипные блоки). Padding уместнее, т.к. мы говорим не о расположение крупных блоков, влияющих на весь сайт, а о позиционировании более мелких блоков в рамках одного большого.

2017-05-22 22:18 UTC, Afelua commented on style.css
> +  background-color: white;
Наследуется

2017-05-22 22:18 UTC, Afelua commented on style.css
> +  left: 663px;
Большое значение слева - плохо. Постараться выровнить относительно центра самой линии, для этого задать у нее position: relative;

2017-05-22 22:18 UTC, Afelua commented on style.css
> +  top: -20px;
Отрицательные значения тоже стоит избегать. Уйдет после изменения margin на padding у .timetable__main

2017-05-22 22:18 UTC, Afelua commented on style.css
> +  width: 170px;
А что, если текст не влезет? Лучше делать размер кнопки с помощью padding

2017-05-22 22:18 UTC, Afelua commented on style.css
> +  height: 490px;
height убираем

2017-05-22 22:18 UTC, Afelua commented on style.css
> +  content: "1";
Цифры не по центру кружка, так и должно быть? 
<img width="246" alt="screen shot 2017-05-23 at 01 17 09" src="https://cloud.githubusercontent.com/assets/8777546/26330632/930d4844-3f55-11e7-9206-fb2265171fae.png">

2017-05-22 22:18 UTC, Afelua commented on style.css
> +  text-align: center;
Свойство можно задать для всего catalog__item, оно наследуется, убрать потом у .catalog__subtitle

2017-05-25 17:08 UTC, qsok3d commented on style.css
>  .services{
+

2017-05-25 17:24 UTC, qsok3d commented on style.css
> +  text-align: center;
+

2017-05-25 17:24 UTC, qsok3d commented on style.css
> +  background-color: #fff;
+

2017-05-25 17:26 UTC, qsok3d commented on style.css
> +  height: 535px;
+

2017-05-25 17:27 UTC, qsok3d commented on style.css
> +  background-color: white;
+

2017-05-25 17:34 UTC, qsok3d commented on style.css
> +  padding-top: 60px;
+

2017-05-25 17:34 UTC, qsok3d commented on style.css
> +  top: -20px;
+

2017-05-25 17:43 UTC, qsok3d commented on style.css
> +  left: 663px;
+

2017-05-25 17:46 UTC, qsok3d commented on style.css
> +  height: 490px;
+

2017-05-25 17:46 UTC, qsok3d commented on style.css
> +  content: "1";
+

2017-05-25 23:34 UTC, Afelua approved these changes

2017-05-25 23:34 UTC, merged